var onlineClass = [
    {
      "id": 1,
      "name": "Shopping !",
      "description": "Learn how to do shopping in 1 hour with 25+ simple-to-use rules and guidelines!",
      "enroll": "422,656",
      "vdesc":"46min of on-demand video",
      "seller":"Jonas Schmedtmann",
      "price": 69,
      "img":"https://meaningfullyorganized.com/wp-content/uploads/2016/11/mandalay-bay-retail-resort-shops-shopping-bags.jpg",
    },
    {
        "id": 2,
        "name": "Cooking- The Complete Guide (incl Deshi, Thai, Korean)",
        "description": "Cooking or cookery is the art, technology, science and craft of using heat to prepare food for consumption",
        "enroll": "293,611",
        "vdesc":"40.5 hours on-demand video",
        "seller":"Maximillius Aurchous ",
        "price": 122,
        "img":"https://image.freepik.com/free-photo/board-amidst-cooking-ingredients_23-2147749529.jpg",
    },
    {
        "id": 3,
        "name": "Facebook live",
        "description": "You can go live on a Page, in a group or an event, and your live videos will also appear in people’s News Feed",
        "enroll": "228,581",
        "vdesc":"12hour of on-demand video",
        "seller":"Leanne Graham",
        "price": 121,
        "img":"https://q5n8c8q9.rocketcdn.me/wp-content/uploads/2018/09/Brands-Killing-It-on-Facebook-Live.png",
    },
    {
        "id": 4,
        "name": "Make youtube video for Complete Beginners",
        "description": "Learn to make video in youtube and earn money",
        "enroll": "23,656",
        "vdesc":"6hour of on-demand video",
        "seller":"Ervin Howell",
        "price": 39,
        "img":"https://www.youtube.com/img/desktop/yt_1200.png",
    },
    {
        "id": 5,
        "name": "Learn photograpy ",
        "description": "Advance your Skills By photograpy!",
        "enroll": "121,656",
        "vdesc":"8.5 hours on-demand video",
        "seller":"Clementine Bauch",
        "price": 174,
        "img":"https://www.nousngo.eu/wp-content/uploads/2019/05/photographer-website-design-91250317.jpg",
    },
    {
        "id": 6,
        "name": "How to do business in online",
        "description": "Take this course to for your future!",
        "enroll": "118,132",
        "vdesc":"14 hours on-demand video",
        "seller":"Patricia Lebsack",
        "price": 139,
        "img":"https://image.freepik.com/free-vector/online-shop-store-e-commerce-sale-msacot-cute-logo_8169-157.jpg",
    },
    {
        "id": 7,
        "name": "Evening Snacks Course",
        "description": "The tools, the techniques and the methods!",
        "enroll": "5,902",
        "vdesc":"16.5 hours on-demand video",
        "seller":"Chelsey Dietrich",
        "price": 129,
        "img":"https://www.tarladalal.com/category/Starters---Snacks-Evening-Tea-Snacks-.jpg",
    },
    {
        "id": 8,
        "name": "Swiming Course",
        "description": "The top rated course in online.",
        "enroll": "68,580",
        "vdesc":"38 hours on-demand video",
        "seller":"Mrs. Dennis Schulist",
        "price": 134,
        "img":"https://storage.googleapis.com/afs-prod/media/afs:Medium:8124512284/1024.png",
    },
    {
        "id": 9,
        "name": "Cycling and More!",
        "description": "The most advanced and modern course on the internet.",
        "enroll": "107,109",
        "vdesc":"28 hours on-demand video",
        "seller":"Kurtis Weissnat",
        "price": 184,
        "img":"https://images.vastsverige.com/publishedmedia/zvna2ilpsfihgbgo3rbg/1710071450-3343_webb.png",
    },
    {
        "id": 10,
        "name": "Language Development Bootcamp",
        "description": "From Beginner to Advance with Just One Course! Fully Updated with a Comprehensive Module Dedicated to SwiftUI!",
        "enroll": "172,839",
        "vdesc":"58.5 hours on-demand video",
        "seller":"Nicholas Runolfsdottir V",
        "price": 13,
        "img":"https://miro.medium.com/max/11144/1*nNxybrXr-YPikYvaXyDbkQ.jpeg",
    },
    {
        "id": 11,
      "name": "Driving Master Class: Go from Beginner to Expert in ROAD",
      "description": "Driving with safty!",
      "enroll": "11,208 ",
      "vdesc":"36 hours on-demand video",
      "seller":"Glenna ReichertJonas Schmedtmann",
      "price": 24,
      "img":"https://autosulavik.com/wp-content/uploads/2019/07/Safe-Driving.jpg",
      },
      {
        "id": 12,
      "name": "How to get a good Job",
      "description": "Practice,Improve and Job",
      "enroll": "1,466",
      "vdesc":"1.5 hours on-demand video",
      "seller":"Clementina DuBuque",
      "price": 104,
      "img":"https://dpnsee.org/wp-content/uploads/2020/01/Job-vacancy.jpg",
      },
      
  ]

  export default onlineClass;
  